### ISSUE TITLE
v0.12.0 no longer passing circleci

### ISSUE THREAD

**Issue by sudotechie** [signalfx/signalfx-nodejs-tracing#85]
Is this a known issue?

**Comment by andrew-prior** [comment]
We are also facing issues with this package and wonder if it is related to it failing circleci

**Comment by andrew-prior** [comment]
In k8 when we attempt to roll out our pod we get this error: `Error: Cannot find module 'requires-port'
Require stack:
- /home/node/app/node_modules/signalfx-tracing/node_modules/url-parse/index.js
- /home/node/app/node_modules/signalfx-tracing/src/config.js
- /home/node/app/node_modules/signalfx-tracing/src/proxy.js
- /home/node/app/node_modules/signalfx-tracing/index.js
- /home/node/app/app.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
at Function.Module._load (internal/modules/cjs/loader.js:667:27)
at Module.require (internal/modules/cjs/loader.js:887:19)
at require (internal/modules/cjs/helpers.js:74:18)
at Object.<anonymous> (/home/node/app/node_modules/signalfx-tracing/node_modules/url-parse/index.js:3:16)
at Module._compile (internal/modules/cjs/loader.js:999:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
at Module.load (internal/modules/cjs/loader.js:863:32)
at Function.Module._load (internal/modules/cjs/loader.js:708:14)
at Module.require (internal/modules/cjs/loader.js:887:19) {
code: 'MODULE_NOT_FOUND',
requireStack: [
'/home/node/app/node_modules/signalfx-tracing/node_modules/url-parse/index.js',
'/home/node/app/node_modules/signalfx-tracing/src/config.js',
'/home/node/app/node_modules/signalfx-tracing/src/proxy.js',
'/home/node/app/node_modules/signalfx-tracing/index.js',
'/home/node/app/app.js'
]
}`

**Comment by jtmalinowski** [comment]
@andrew-prior are you saying that `0.11.0` worked for you and after updating to `0.12.0` you're getting the above error?
